### ISSUE TITLE
Support merging directories

### ISSUE THREAD

**Issue by danielpza** [fabiomcosta/mvjs#9]
When moving a directory if it already exist it throws an error. I would be useful if it merges the directories instead.

**Comment by fabiomcosta** [comment]
Makes sense!
I'll add this when I get some time

**Comment by fabiomcosta** [comment]
I believe this fixes this issue: https://github.com/fabiomcosta/mvjs/commit/169141748d65d939a7e8b1a42800bdd9876eda3d#diff-91ba5f4df12e1b6b0629662164b3f14eR68

And I believe this issue was only happening when moving a single file into a folder, if you tried moving more files it was probably working.
Try out 1.14.1 and let me know!

**Comment by danielpza** [comment]
Yeah it works, I forgot I opened this issue. Thanks for your work!
